### ISSUE TITLE
Trending doesn't show anything 

### ISSUE THREAD

**Issue by glitzflitz** [thermatk/FastHub#112]
**FastHub-Libre Version: 4.6.7**  
**Android Version: 6.0.1 (SDK: 23)**  
**Device Information:**  
- **Manufacturer:** asus  
- **Brand:** asus  
- **Model:** ASUS_Z010D  
---

As the title says trending page doesn't show anything even after filtering language

**Comment by quantumpacket** [comment]
@glitzflitz This has already been reported #90, #94, #108

**Comment by glitzflitz** [comment]
Oh Ok. I'll close this issue then
