### ISSUE TITLE
Failed to load image on Select, uploading issues

### ISSUE THREAD

**Issue by rancidfrog** [thermatk/FastHub#12]
When using select to upload images automatically, using imgur api I believe, I keep getting `Failed to load image`:
![](https://s17.postimg.org/kjayo0mgf/Screenshot_20171114-100444_01.png)

It might be due to API keys, as it seems to work upstream.

**Comment by thermatk** [comment]
![Test](https://i.imgur.com/LgqSnIY.png)

**Comment by thermatk** [comment]
Test
![Test](https://i.imgur.com/5EzbuX4.png)

**Comment by rancidfrog** [comment]
I keep getting error.
Is it handled any differently from upstream?

**Comment by rancidfrog** [comment]
It fails when I choose gallery app for some reason, probably issue with app or change of code. 
![](https://i.imgur.com/Fu1lyjX.png)

Works when I choose image, so sorry for that. As gallery works on web uploads from browser
