### ISSUE TITLE
How to donate to FastHub-Libre, not to FastHub?

### ISSUE THREAD

**Issue by Kaned1as** [thermatk/FastHub#16]
I'm also thankful for the effort spent for submitting it to F-Droid, but there's no option to donate to you.

**Comment by thermatk** [comment]
Hi!
Added the option :)
https://liberapay.com/thermatk/

**Comment by Kaned1as** [comment]
Looks like Liberapay has trust issues with me, sorry

![image](https://user-images.githubusercontent.com/863272/34342331-0a51ac3e-e9be-11e7-8b53-ae987522a97d.png)

**Comment by thermatk** [comment]
Whenever I try to open accounts on most other services I tried, they either block me or money withdrawals until I change my citizenship, so it's the same in reverse 😢 
@Adonai which country is it?

**Comment by Kaned1as** [comment]
Russia it is. Strange for me too.
Have you tried Patreon?

**Comment by thermatk** [comment]
Russia2Russia is comparatively easy 😀 
http://yasobe.ru/na/thermatk

**Comment by Kaned1as** [comment]
So my suspicion was correct }:->

Will do when I'm home.
Happy new year!

**Comment by Kaned1as** [comment]
Done.

**Comment by Kaned1as** [comment]
Wanted to say one more thing.

I appreciate your belief in libre software. You know that freedom matters.
Keep up the good work.

**Comment by thermatk** [comment]
@Adonai thank you and happy New Year!

P.S. Started spending 😄 
![foto](https://user-images.githubusercontent.com/2287483/34376115-76fd386c-eaea-11e7-91fc-2cad9b58a21e.jpg)
