### ISSUE TITLE
Unable to install latest releases on Android 8.1

### ISSUE THREAD

**Issue by rushilsrivastava** [thermatk/FastHub#23]
**FastHub-Libre Version: 4.5.5**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** Google  
- **Model:** Pixel 2 XL  
---

Hi, the app installs perfectly fine from when I download it from F-Droid, but F-Droid doesn't have the latest version, and I am unable to download it from the release page (.app doesn't open up in system installer)

Any suggestions?

Thanks!

**Comment by rushilsrivastava** [comment]
I went ahead and compiled from source for the time being. Do you plan to release future updates on F-Droid?

**Comment by thermatk** [comment]
Hi!
Versions from different sources can't be installed over each other, due to signatures. F-Droid build server has been broken for a month already and failed building new updates for its own reasons, but will be fixed soon, I hope

**Comment by rushilsrivastava** [comment]
@thermatk Gotcha. Thanks for the info. It seems as the F-Droid build server seems to be passing and working now.
