### ISSUE TITLE
Error toast when commenting a pr, but comment is sent

### ISSUE THREAD

**Issue by mueller-ma** [thermatk/FastHub#30]
**FastHub-Libre Version: 4.6.1**  
**Android Version: 7.1.2 (SDK: 25)**  
**Device Information:**  
- **Manufacturer&Brand:** OnePlus  
- **Model:** OnePlus  
---

Since the last update, I get a toast "Error while communicating with the server" every time I comment on an issue or pr, but the comment is actually sent.

**Comment by thermatk** [comment]
Can confirm, will sync with upstream when I'm done with studies

**Comment by thermatk** [comment]
Fixed
