### ISSUE TITLE
Gitea/Gogs support

### ISSUE THREAD

**Issue by Serkan-devel** [thermatk/FastHub#33]
It would be great to have local Github-like services to be accessed within this app.

(Upstream seams to have declined it https://github.com/k0shk0sh/FastHub/issues/1459 - only applies for gitlab)

**Comment by thermatk** [comment]
I would say it's almost impossible and means writing a whole separate app. Gitlab has different APIs, FastHub is built around Github's endpoints

**Comment by fazlerabbi37** [comment]
@thermatk maybe I am wrong but to me it seems Gogs and Gitea have almost identical API endpoint of GitHub. Would you consider adding those two?

**Comment by Serkan-devel** [comment]
Maybe one should be able to configure the url endpoint for supporting different git hosts as with gogs/gitea

**Comment by 4oo4** [comment]
That would be awesome if this gets picked up, in the meantime there's this:

https://gitlab.com/mmarif4u/gitnex

**Comment by Serkan-devel** [comment]
I guess upstream won't support gitea https://github.com/k0shk0sh/FastHub/issues/2350

**Comment by Serkan-devel** [comment]
Could this issue be reopened?

**Comment by unfa** [comment]
I'm using both GitHub and Gitea and being able to use FastHub-Libre with both would be fantastic for me.
Can I help?
