### ISSUE TITLE
right sidebar breaks scrolling

### ISSUE THREAD

**Issue by matthiaskrgr** [thermatk/FastHub#35]
I just updated fasthub libre from fdroid.

Is there a way to disable the sidebar comming from the right?
When scrolling by touching the scroll-bar handle (the blue thing), for example when viewing a list of PRs or issues, a very slight move to the left will trigger the sidebar to pop up and overlay the scroll handle and scrolling stops, this is very annoying, especially when scrolling through very long reports. :/ 

**FastHub Version: 4.6.3**
**Android Version:6.0.1**
**Device Information:nexus 5**

**Comment by matthiaskrgr** [comment]
I tried downgrading to 4.6.2 but it fails "due to an unknown error" :(

**Comment by thermatk** [comment]
@matthiaskrgr downgrades are not allowed on android, I'm surprised it's not reported upstream

**Comment by thermatk** [comment]
Seems to be fixed upstream, will release shortly
https://github.com/k0shk0sh/FastHub/issues/1625

**Comment by thermatk** [comment]
released, wait for fdroid
